version: "3"
services:
  # The application image
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
      - "9222:9222" # debug port node for inspect-brk
    command: yarn dev